<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
گل‌های زنبق
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش اول - بارگیری داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
ابتدا آرایه‌های مورد نیازمان را بارگیری می‌کنیم. هم‌چنین تعداد نمونه‌های آموزش را <code>n</code> و تعداد نمونه‌های آزمون را <code>m</code> می‌نامیم. 
</font>
</p>

In [2]:
import numpy as np
irises = np.load('irises.npy')
types = np.load('types.npy')
new_irises = np.load('new_irises.npy')
print(irises.shape)
print(types.shape)
print(new_irises.shape)
n, m = len(irises), len(new_irises)

(120, 4)
(120,)
(30, 4)


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش دوم - محاسبه فاصله‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
ابتدا با کمک دو حلقه در تابع <code>calc_two_loops</code>، مجذور فاصله‌ها را محاسبه کرده و برمی‌گردانیم. برای این منظور کافیست عبارتی را جلوی تساوی قرار دهید که برابر با مجذور فاصله دو نقطه <code>new_points[i]</code> و <code>points[j]</code> است (چون جذر گرفتن تاثیری بر فاصله نسبی نقطه‌ها ندارد، به مجذور فاصله اکتفا می‌کنیم).
</font>
</p>

In [3]:

def calc_two_loops(new_points, points):
    m, n = len(new_points), len(points)
    d = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            
            d[i,j]=sum((new_points[i,:] - points[j,:])**2)
            
    return(d)


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در ادامه، همین کار را به کمک یک حلقه در تابع <code>calc_one_loop</code> انجام می‌دهیم. این بار جلوی تساوی، عبارتی را بنویسید که سطر <code>i</code>ام آرایه مجذور فاصله‌ها را نتیجه دهد.
</font>
</p>

In [4]:

def calc_one_loop(new_points, points):
    
    m, n = len(new_points), len(points)   
    d = np.zeros((m,n))
    for i in range(m):
        
        d[i]=sum((new_points[i,:].reshape(-1,1) - points.T)**2)
    
    return(d)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
        در نهایت همین کار را بدون حلقه در تابع <code>calc_no_loop</code> انجام می‌دهیم. این بار جلوی <code>return</code>، عبارتی را در یک خط بنویسید که حاصل آن کل آرایه مجذور فاصله‌ها باشد!
        <br>
راهنمایی: در این بخش و بخش قبلی باید از خاصیت پخش آرایه‌ها استفاده کنید. برای این منظور، می‌توانید آرایه‌ها را بازآرایی کنید.
</font>
</p>

In [5]:

def calc_no_loop(new_points, points):
    return(np.sum(np.square(np.subtract(new_points[:,np.newaxis],points)),axis=2))
   

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
ممکن است ساختن آرایه فاصله‌ها بدون حلقه، پیچیده به نظر برسد. اما استفاده از خاصیت پخش آرایه‌ها به جای استفاده از حلقه هم باعث سریع‌تر شدن کد و هم کوتاه‌تر شدن آن می‌شود و خوب است به آن عادت کنید. سریع‌تر شدن کد را می‌توانید با ورودی دادن آرایه‌های بزرگ بیازمایید.         
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
محاسبه آرایه فاصله‌ها به سه روش فوق، نباید تفاوتی در نتیجه حاصل کند. از این رو کد زیر را اجرا کنید تا از برابر بودن خروجی سه تابع فوق اطمینان حاصل کنید. از این به بعد از آرایه ‍<code>d</code> به عنوان آرایه فاصله‌ها استفاده می‌کنیم.
</font>
</p>

In [6]:
d2 = calc_two_loops(new_irises, irises)
d1 = calc_one_loop(new_irises, irises)
d = calc_no_loop(new_irises, irises)

if np.allclose(d, d1, 1e-5) and np.allclose(d, d2, 1e-5):
    print('Fine!')
else:
    print('There is something wrong!')

Fine!


<h2 dir = rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش سوم - پیدا کردن <code>k</code> نزدیک‌ترین همسایه
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در ادامه، مقدار <code>k</code> را برابر ۱۰ قرار داده‌ایم. حال در برابر تساوی عبارتی بنویسید که آرایه‌ای <code>(m, k)</code> را خروجی دهد و در سطر <code>i</code> آن شماره <code>j</code> قرار گیرد اگر <code>irises[j]</code> جزو <code>k</code> تا نزدیک‌ترین نمونه آموزش به <code>new_irises[i]</code> باشد.
        <br>
راهنمایی: در مورد تابع <code>argpartition</code> نامپای و تفاوت آن با تابع <code>partition</code> که در این فصل آموختیم، تحقیق کنید.
</font>
</p>

In [7]:
k = 10
k_nearest = np.argpartition(d,k,axis=1)[:,:10]
k_nearest

array([[  6,  14,   0,  32,  22,  17,  39,  21,  23,  37],
       [ 10,   1,  30,  24,  20,   2,  36,   3,   6,  28],
       [ 27,  13,   8,  39,   4,  29,  15,  12,  26,  25],
       [ 14,  17,   0,  39,  37,  22,   8,  32,  26,  13],
       [ 21,  20,  30,   3,   9,  24,   6,  19,  35,   5],
       [ 10,   1,   2,   3,  38,   5,  36,  30,  24,   9],
       [ 10,   1,  30,  24,  20,   2,  36,   3,   6,  28],
       [  0,   6,  22,  23,  21,  14,   9,  32,  17,  39],
       [ 39,  35,  17,  22,   4,  21,  37,  19,   8,  16],
       [ 28,   6,  23,   0,  14,  21,  30,  32,  22,   9],
       [ 47,  73,  69,  61,  52,  51,  41,  60, 101,  58],
       [ 71,  43,  65,  64,  77,  72,  66,  76,  74,  54],
       [ 71,  65,  74,  64,  66,  77,  76,  54,  57,  49],
       [ 64,  65,  74,  66,  43,  50,  54,  72,  77,  71],
       [ 78,  60,  47,  41,  73,  52,  63,  57,  51,  59],
       [ 74,  65,  54,  64,  66,  43,  50,  57,  71,  75],
       [ 77,  71,  44,  53,  72,  76,  49,  97,  56,  63

<h2 dir = rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش چهارم - پیدا کردن نوع <code>k</code> نزدیک‌ترین همسایه
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
حالا آرایه <code>k_nearest_types</code> را در یک خط مقداردهی کنید؛ طوری که هم‌شکل <code>k_nearest</code> باشد، اما به جای شماره هر نمونه آموزش شناسه نوع آن قرار گیرد.        
</font>
</p>

In [8]:
k_nearest_types = types[k_nearest]
k_nearest_types

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 2, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [2, 1, 2, 2, 1, 2, 2, 2, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2,

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش پنجم - تعیین نوع گل‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در نهایت، باید آرایه <code>predicted_types</code> به طول <code>m</code> را بسازیم که در خانه <code>predicted_types[i]</code>، پرتکرارترین شناسه در <code>k_nearest_types[i]</code> به عنوان شناسه نوع پیش‌بینی شده برای <code>new_irises[i]</code> قرار می‌گیرد. این کار را به کمک تابع <code>mode</code> که داخل کتابخانه <code>scipy</code> قرار دارد، انجام داده‌ایم.
</font>
</p>

In [9]:
from scipy import stats

In [10]:
predicted_types = stats.mode(k_nearest_types, axis=1).mode.reshape(m)
predicted_types

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
پس از آن، آرایه <code>new_types</code> بارگیری شده‌است که حاوی جواب‌های درست است. از روی آن، دقت دسته‌بندی‌ را محاسبه و در متغیر <code>accuracy</code> ذخیره کنید. دقت دسته‌بندی برابر با تعداد پیش‌بینی‌های درست تقسیم بر تعداد نمونه‌های آزمون است. اگر مراحل کار را درست انجام داده‌باشید، دقت باید برابر ۱ باشد (یعنی دسته‌بند همه نوع گل‌ها را درست پیش‌بینی می‌کند).
</font>
</p>

In [11]:
new_types = np.load('new_types.npy')
accuracy =len(predicted_types) / len(new_types)
print('Accuracy:', accuracy)

Accuracy: 1.0


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
به کمک سلول زیر، کد خود را به همراه جوابتان فشرده کرده و فایل result.zip را درون سامانه بارگذاری کنید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

In [ ]:
import zipfile
from inspect import getsource

np.savez("answers.npz", k_nearest = k_nearest, k_nearest_types = k_nearest_types, predicted_types = predicted_types)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)

imp = 'import numpy as np\n'
%save calc_two_loops imp + getsource(calc_two_loops)
%save calc_one_loop imp + getsource(calc_one_loop)
%save calc_no_loop imp + getsource(calc_no_loop)

file_names = ["calc_two_loops.py", "calc_one_loop.py", "calc_no_loop.py",
              "answers.npz", "iris_flowers.ipynb"]
compress(file_names)